# Generated by Django 5.0.3 on 2024-03-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(blank=True, max_length=30)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('emprestado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
